In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'C:\Users\ALLAN\Desktop\github\data cleaning\netflix_titles.csv')

In [3]:
#overview of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   show_id         8807 non-null   object
 1   type            8807 non-null   object
 2   title           8807 non-null   object
 3   director        8807 non-null   object
 4   cast            8807 non-null   object
 5   country         8807 non-null   object
 6   date_added      8797 non-null   object
 7   release_year    8807 non-null   int64
 8   rating          8803 non-null   object
 9   duration        8804 non-null   object
 10  listed_in       8807 non-null   object
 11  duration_value  8804 non-null   float64
 12  duration_unit   8804 non-null   object
dtypes: float64(1), int64(1), object(11)
memory usage: 894.6+ KB

In [4]:
#number of rows and columns
df.shape

(8807, 13)

In [5]:
#list of all column names
df.columns.tolist()

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'duration_value',
 'duration_unit']

In [6]:
# datatype of each column
df.dtypes

show_id            object
type               object
title              object
director           object
cast               object
country            object
date_added         object
release_year        int64
rating             object
duration           object
listed_in          object
duration_value    float64
duration_unit      object
dtype: object

In [7]:
#Grouping and counting missing values in each column
df.isnull().sum()

show_id            0
type               0
title              0
director           0
cast               0
country            0
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
duration_value     3
duration_unit      3
dtype: int64

In [8]:
##Grouping and counting duplicate values in each column
df.duplicated().sum()

0

In [9]:
#Structuring
#convert 'date_added'to datetime
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [10]:
#separating duration into numeric value
df[['duration_value','duration_unit']]= df['duration'].str.extract(r'(\d+)\s*(\w+)')
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,duration_value,duration_unit
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Given,United States,2021-09-25,2020,PG-13,90 min,Documentaries,90,min
1,s2,TV Show,Blood & Water,Not Given,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",2,Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...","France, Belgium",2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",1,Season
3,s4,TV Show,Jailbirds New Orleans,Not Given,Not Given,Not Given,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV",1,Season
4,s5,TV Show,Kota Factory,Not Given,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",2,Seasons
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers",158,min
8803,s8804,TV Show,Zombie Dumb,Not Given,Not Given,Not Given,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies",2,Seasons
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",88,min
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies",88,min
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",111,min

In [11]:
#converting duration_value to numeric
df['duration_value']=pd.to_numeric(df['duration_value'])
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,duration_value,duration_unit
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Given,United States,2021-09-25,2020,PG-13,90 min,Documentaries,90.0,min
1,s2,TV Show,Blood & Water,Not Given,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",2.0,Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...","France, Belgium",2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",1.0,Season
3,s4,TV Show,Jailbirds New Orleans,Not Given,Not Given,Not Given,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV",1.0,Season
4,s5,TV Show,Kota Factory,Not Given,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",2.0,Seasons
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers",158.0,min
8803,s8804,TV Show,Zombie Dumb,Not Given,Not Given,Not Given,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies",2.0,Seasons
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",88.0,min
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies",88.0,min
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",111.0,min

In [12]:
#Viewing resulting columns
print(df[['duration_value','duration_unit']])

      duration_value duration_unit
0               90.0           min
1                2.0       Seasons
2                1.0        Season
3                1.0        Season
4                2.0       Seasons
...              ...           ...
8802           158.0           min
8803             2.0       Seasons
8804            88.0           min
8805            88.0           min
8806           111.0           min

[8807 rows x 2 columns]

In [13]:
#Cleaning
#check duplicates/
df.duplicated().sum()

0

In [14]:
#drop duplicated rows
df=df.drop_duplicates()

In [ ]:
#impute Director values by using relationship between cast and director
df['dir_cast']=df['director']+'--'+ df['cast']
counts = df['dir_cast'].value_counts()

In [ ]:
#counts unique values
filtered_counts =counts[counts>=3]

In [ ]:
#check if repeated 3 or more times
filtered_values=filtered_counts.index

In [ ]:
#getting the values 
lst_dir_cast= list(filtered_values)
dict_direcast=dict()
for i in lst_dir_cast:
    director,cast = i.split('--')
    dict_direcast[director]= cast
for i in range(len(dict_direcast)):
    df.loc[(df['director'].isna())&(df['cast']==list(dict_direcast.items())[1]),'director'] = list(dict_direcast.items())[1][0]

In [ ]:
#Assign not given to all other director
df.loc[df['director'].isna(),'director']= 'Not Given'

In [ ]:
#directors to fill missing countries
directors = df['director']
countries = df['country']

In [ ]:
#pairing each directors with their country
pairs = zip(directors,countries)

In [ ]:
#converting the list of tuples into a dictionary
dir_cntry =dict(list(pairs))

In [ ]:
#director matched to country values to fill in null country values
for i in range (len(dir_cntry)):
    df.loc[(df['country'].isna())&(df['director']==list(dir_cntry.items())[i][0]),'country']=list(dir_cntry.items())[i][1]

In [ ]:
#assigning NOT GIVEN to all other country field
df.loc[df['country'].isna(),'country'] = 'Not Given'

In [ ]:
##assigning NOT GIVEN to all field
df.loc[df['cast'].isna(),'cast'] = 'Not Given'

In [ ]:
#dropping other row records with null
df.drop(df[df['date_added'].isna()].index,axis)
df.drop(df[df['rating'].isna()].index,axis = 0,input =True)
df.drop(df[df['duration'].isna()].index,axis=0,input =True)

In [17]:
#checking if any added_datesthat comes before release_year
import datetime as dt
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
sum(df['date_added'].dt.year < df['release_year'])
df.loc[(df['date_added'].dt.year < df['release_year']),
['date_added','release_year']]

     date_added  release_year
1551 2020-12-14          2021
1696 2020-11-15          2021
2920 2020-02-13          2021
3168 2019-12-06          2020
3287 2019-11-13          2020
3369 2019-10-25          2020
3433 2019-10-11          2020
4844 2018-05-30          2019
4845 2018-05-29          2019
5394 2017-07-01          2018
5658 2016-12-23          2018
5677 2016-12-13          2017
7063 2018-10-26          2019
7112 2013-03-31          2016

In [16]:
sum(df['date_added'].dt.year < 
   df['release_year'])

14

In [ ]:
#df.drop(columns = ['dir_cast'],inplace= True)

In [19]:
df.sample(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,duration_value,duration_unit
3848,s3849,TV Show,Cinta Teruna Kimchi,Not Given,"Nazim Othman, Johan As'ari, Nur Risteena, Nien...",Not Given,2019-05-08,2016,TV-PG,1 Season,"International TV Shows, TV Dramas",1.0,Season
4901,s4902,Movie,The Clapper,Dito Montiel,"Ed Helms, Amanda Seyfried, Tracy Morgan, Brend...",United States,2018-05-01,2017,R,90 min,"Comedies, Dramas, Independent Movies",90.0,min
1274,s1275,TV Show,Canine Intervention,Not Given,Jas Leverette,United States,2021-02-24,2021,TV-PG,1 Season,Reality TV,1.0,Season
3336,s3337,TV Show,Haikyu!!,Not Given,"Ayumu Murase, Kaito Ishikawa, Satoshi Hino, Mi...",Japan,2019-11-01,2015,TV-14,2 Seasons,"Anime Series, International TV Shows, Teen TV ...",2.0,Seasons
3752,s3753,TV Show,Marvel's Jessica Jones,Not Given,"Krysten Ritter, David Tennant, Rachael Taylor,...",United States,2019-06-14,2019,TV-MA,3 Seasons,"Crime TV Shows, TV Action & Adventure, TV Dramas",3.0,Seasons

In [20]:
df_reset = df.reset_index(drop=True)
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,duration_value,duration_unit
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Not Given,United States,2021-09-25,2020,PG-13,90 min,Documentaries,90.0,min
1,s2,TV Show,Blood & Water,Not Given,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",2.0,Seasons
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...","France, Belgium",2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",1.0,Season
3,s4,TV Show,Jailbirds New Orleans,Not Given,Not Given,Not Given,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV",1.0,Season
4,s5,TV Show,Kota Factory,Not Given,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",2.0,Seasons
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers",158.0,min
8803,s8804,TV Show,Zombie Dumb,Not Given,Not Given,Not Given,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies",2.0,Seasons
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",88.0,min
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies",88.0,min
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",111.0,min

In [ ]:
df.to_csv(r'C:\Users\ALLAN\Desktop\github\data cleaning\netflix_titles.csv', index=False)